import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy — Hey Otis',
  description:
    'How Hey Otis handles your data. Privacy by design — what we collect, how AI processes your input, encryption, your rights, and how to delete your data.',
};

const SECTIONS: { title: string; body: React.ReactNode }[] = [
  {
    title: 'What data we collect',
    body: (
      <>
        <p>Hey Otis collects only the data you provide directly:</p>
        <ul>
          <li>Your name and relationship profile (attachment style, love language, conflict style, body response, core need)</li>
          <li>Session messages and reflections you write during guided conversations</li>
          <li>Emotional check-in scores you record</li>
          <li>Partner observations and relationship patterns you add to your learnings</li>
          <li>Your email address (if you create an account)</li>
          <li>Optional demographic information you choose to share during onboarding: age, gender, country, relationship status, whether you have children, and how you heard about Hey Otis. Every one of these is skippable.</li>
          <li>Anonymous product usage events (which screens you visit, when a session starts, onboarding step completion). Used only to improve the product. Sent to PostHog (see &ldquo;Data sharing&rdquo;).</li>
        </ul>
        <p>
          We do <strong>not</strong> collect precise device location, contact lists, browsing history, or any data from other apps on your device. The country field is self-reported text, not derived from GPS or IP.
        </p>
      </>
    ),
  },
  {
    title: 'How AI processes your data',
    body: (
      <>
        <p>Hey Otis uses Anthropic&apos;s Claude AI to power guided conversations and generate insights.</p>
        <ul>
          <li>Your session messages are sent to the Anthropic API to generate responses during active conversations.</li>
          <li>Session summaries and memory narratives are generated by the AI to provide continuity across sessions.</li>
          <li>
            Your data is <strong>not used to train AI models</strong>. Anthropic&apos;s API usage policy explicitly states that API inputs and outputs are not used for model training.
          </li>
          <li>Each conversation is processed independently. The AI does not retain information between API calls beyond what Hey Otis explicitly provides as context.</li>
          <li>AI responses are suggestions for self-reflection, not clinical diagnoses or professional advice.</li>
        </ul>
      </>
    ),
  },
  {
    title: 'Data encryption and storage',
    body: (
      <>
        <p>Your data is protected through the following layers:</p>
        <ul>
          <li>Authentication tokens are stored in your device&apos;s secure keychain (iOS Keychain / Android Keystore via expo-secure-store), using hardware-backed encryption where available.</li>
          <li>Data transmitted to our servers uses TLS 1.2+ encryption in transit.</li>
          <li>Server-side data is stored in Supabase (EU region) with AES-256 encryption at rest and row-level security policies, ensuring you can only access your own data.</li>
          <li>Your vent sessions and private reflections are never visible to your partner, even if you are connected. This is enforced at the database layer.</li>
        </ul>
        <p>
          Session content and profile data are also cached locally on your device so the app works offline. On iOS and Android this cache is protected by the operating system&apos;s app sandbox — other apps cannot read it. The cache is cleared when you sign out or delete your account.
        </p>
      </>
    ),
  },
  {
    title: 'Data sharing',
    body: (
      <>
        <p>We do not sell or rent your personal data. We share data only with the limited processors below:</p>
        <ul>
          <li>Your data is never sold to advertisers or data brokers.</li>
          <li><strong>Anthropic (Claude API)</strong> — processes your session messages to generate AI responses, under a Data Processing Agreement. Anthropic does not use your data to train models.</li>
          <li><strong>Supabase</strong> — hosts your account and profile data in the EU region with row-level security so only you can read your own rows.</li>
          <li><strong>PostHog (EU region)</strong> — receives anonymous product usage events (taps, screen views, session starts, onboarding step completion) so we can see which features are used and improve the product. We do not send your session content, messages, or reflections to PostHog. Tracking begins only after you accept the consent gate; you can opt out at any time by deleting your account.</li>
          <li>If you connect with a partner, only your name and profile-type results are shared with them. Your session content remains private.</li>
        </ul>
      </>
    ),
  },
  {
    title: 'Crisis safety logging',
    body: (
      <>
        <p>If your input matches one of the crisis patterns documented in our safety framework (suicide, self-harm, abuse, child safety, psychosis, substance crisis, or eating-disorder crisis), Hey Otis will:</p>
        <ul>
          <li>Surface country-appropriate helpline resources immediately.</li>
          <li>Skip the AI response entirely — your message is not sent to the language model.</li>
          <li>Record the event category (not the message content) in an internal audit log so we can review pattern coverage.</li>
        </ul>
        <p>The audit log stores the category, timestamp, and a 120-character excerpt of the input — it never stores the full conversation content.</p>
      </>
    ),
  },
  {
    title: 'Your rights',
    body: (
      <>
        <p>Under applicable data protection laws (including GDPR), you have the following rights:</p>
        <ul>
          <li><strong>Right of access:</strong> You can view all your data within the app at any time. Use &ldquo;Export my data&rdquo; in Settings to download a complete copy.</li>
          <li><strong>Right to deletion:</strong> You can delete all your data at any time using &ldquo;Delete all my data&rdquo; in Settings. This permanently removes your account, sessions, messages, learnings, and profile data.</li>
          <li><strong>Right to portability:</strong> The data export feature provides your data in a standard JSON format that you can take with you.</li>
          <li><strong>Right to rectification:</strong> You can update your profile information at any time by retaking onboarding or editing your settings.</li>
          <li><strong>Right to withdraw consent:</strong> You can stop using AI features at any time. Deleting your account removes all data from our systems.</li>
          <li><strong>Right to lodge a complaint:</strong> You can complain to your local data protection authority if you believe we have not handled your data properly.</li>
        </ul>
      </>
    ),
  },
  {
    title: 'Sub-processors',
    body: (
      <>
        <p>We use the following sub-processors to deliver Hey Otis. Each is bound by a Data Processing Agreement and EU-aligned data handling.</p>
        <ul>
          <li><strong>Supabase</strong> (EU region, Frankfurt) — database, authentication, edge functions</li>
          <li><strong>Anthropic</strong> — Claude AI for guided conversations, under zero-retention API terms</li>
          <li><strong>Vercel</strong> — hosting for this website</li>
          <li><strong>Apple App Store / Google Play</strong> — app distribution</li>
        </ul>
      </>
    ),
  },
  {
    title: 'How to delete your data',
    body: (
      <>
        <p>To permanently delete all your data:</p>
        <ol>
          <li>Open Hey Otis and go to Settings.</li>
          <li>Scroll to &ldquo;Privacy and safety&rdquo;.</li>
          <li>Tap &ldquo;Delete all my data&rdquo;.</li>
          <li>Confirm the deletion.</li>
        </ol>
        <p>This action is irreversible. All your sessions, messages, learnings, profile data, and account will be permanently removed within 30 days.</p>
        <p>If you cannot access the app, email <a href="mailto:privacy@heyotis.app">privacy@heyotis.app</a> and we will action the deletion within 30 days.</p>
      </>
    ),
  },
  {
    title: 'Children',
    body: (
      <>
        <p>Hey Otis is intended for adults aged 18 and over. The app is not designed for, marketed to, or appropriate for minors. If you believe a child has created an account, please contact us at <a href="mailto:privacy@heyotis.app">privacy@heyotis.app</a> and we will remove the account.</p>
      </>
    ),
  },
  {
    title: 'Changes to this policy',
    body: (
      <>
        <p>We may update this policy occasionally. Material changes will be communicated in-app and via email. The &ldquo;effective date&rdquo; at the top reflects the latest revision.</p>
      </>
    ),
  },
  {
    title: 'Contact',
    body: (
      <>
        <p>For questions about your privacy or to exercise your data rights:</p>
        <p><strong>Email:</strong> <a href="mailto:privacy@heyotis.app">privacy@heyotis.app</a></p>
        <p>We aim to respond to all privacy-related enquiries within 30 days.</p>
        <p>
          <strong>Data controller:</strong> Hey Otis (10 8 City B.V.), Amsterdam, Netherlands. EU representative details are available on request.
        </p>
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <main className="doc-main">
      <nav className="nav">
        <div className="nav-inner">
          <div className="nav-brand">
            <Link href="/"><img src="/header-logo.png" alt="Hey Otis" className="nav-icon" /></Link>
          </div>
          <Link href="/" className="nav-cta">Back to site</Link>
        </div>
      </nav>

      <article className="doc-article">
        <header className="doc-header">
          <p className="doc-eyebrow">PRIVACY POLICY</p>
          <h1 className="doc-h1">How Hey Otis handles your data.</h1>
          <p className="doc-lede">
            Hey Otis is built on the principle of privacy by design. Your relationship is personal,
            and your data should be too. This page explains exactly what we collect, how it&apos;s
            used, and the control you have over it.
          </p>
          <p className="doc-effective">Effective date: 11 May 2026</p>
        </header>

        <div className="doc-toc">
          <p className="doc-toc-label">CONTENTS</p>
          <ol>
            {SECTIONS.map((s, i) => (
              <li key={i}><a href={`#sec-${i}`}>{s.title}</a></li>
            ))}
          </ol>
        </div>

        {SECTIONS.map((section, i) => (
          <section key={i} id={`sec-${i}`} className="doc-section">
            <h2 className="doc-h2">{section.title}</h2>
            <div className="doc-body">{section.body}</div>
          </section>
        ))}

        <p className="doc-foot">
          See also: <Link href="/terms">Terms of Service</Link>.
        </p>
      </article>

      <footer className="ft">
        <p className="ft-brand">Hey Otis</p>
        <p className="ft-disc">Hey Otis supports but does not replace professional therapy.</p>
        <p className="ft-copy">&copy; 2026 Hey Otis. All rights reserved. &nbsp;|&nbsp; <a href="mailto:privacy@heyotis.app">privacy@heyotis.app</a></p>
      </footer>
    </main>
  );
}
