import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Colors, Fonts, Radius } from '../src/constants/theme';
import { IconX } from '../src/components/Icons';

const SECTIONS = [
  {
    title: 'What data we collect',
    content:
      'Hey Otis collects only the data you provide directly:\n\n' +
      '- Your name and relationship profile (attachment style, love language, conflict style, body response, core need)\n' +
      '- Session messages and reflections you write during guided conversations\n' +
      '- Emotional check-in scores you record\n' +
      '- Partner observations and relationship patterns you add to your learnings\n\n' +
      'We do not collect location data, contact lists, browsing history, or any data from other apps on your device.',
  },
  {
    title: 'How AI processes your data',
    content:
      'Hey Otis uses Anthropic\'s Claude AI to power guided conversations and generate insights.\n\n' +
      '- Your session messages are sent to the Anthropic API to generate responses during active conversations.\n' +
      '- Session summaries and memory narratives are generated by the AI to provide continuity across sessions.\n' +
      '- Your data is NOT used to train AI models. Anthropic\'s API usage policy explicitly states that API inputs and outputs are not used for model training.\n' +
      '- Each conversation is processed independently. The AI does not retain information between API calls beyond what Hey Otis explicitly provides as context.\n' +
      '- AI responses are suggestions for self-reflection, not clinical diagnoses or professional advice.',
  },
  {
    title: 'Data encryption and storage',
    content:
      'Your data is protected through the following layers:\n\n' +
      '- Authentication tokens are stored in your device\'s secure keychain (iOS Keychain / Android Keystore via expo-secure-store), using hardware-backed encryption where available.\n' +
      '- Data transmitted to our servers uses TLS 1.2+ encryption in transit.\n' +
      '- Server-side data is stored in Supabase with AES-256 encryption at rest and row-level security policies, ensuring you can only access your own data.\n' +
      '- Your vent sessions and private reflections are never visible to your partner, even if you are connected. This is enforced at the database layer.\n\n' +
      'Session content and profile data are also cached locally on your device so the app works offline. On iOS and Android this cache is protected by the operating system\'s app sandbox, so other apps cannot read it. The cache is cleared when you sign out or delete your account.',
  },
  {
    title: 'Data sharing',
    content:
      'We do not sell, rent, or share your personal data with third parties.\n\n' +
      '- Your data is never sold to advertisers or data brokers.\n' +
      '- We do not share your data with third-party analytics or marketing platforms.\n' +
      '- The only external service that processes your data is Anthropic\'s Claude API, solely for generating AI responses during your sessions.\n' +
      '- If you connect with a partner, only your name and profile type results are shared with them. Your session content remains private.',
  },
  {
    title: 'Your rights',
    content:
      'Under applicable data protection laws (including GDPR and POPIA), you have the following rights:\n\n' +
      'Right of access: You can view all your data within the app at any time. Use "Export my data" in Settings to download a complete copy.\n\n' +
      'Right to deletion: You can delete all your data at any time using "Delete all my data" in Settings. This permanently removes your account, sessions, messages, learnings, and profile data.\n\n' +
      'Right to portability: The data export feature provides your data in a standard JSON format that you can take with you.\n\n' +
      'Right to rectification: You can update your profile information at any time by retaking onboarding or editing your settings.\n\n' +
      'Right to withdraw consent: You can stop using AI features at any time. Deleting your account removes all data from our systems.',
  },
  {
    title: 'How to delete your data',
    content:
      'To permanently delete all your data:\n\n' +
      '1. Open Hey Otis and go to Settings.\n' +
      '2. Scroll to "Privacy and safety".\n' +
      '3. Tap "Delete all my data".\n' +
      '4. Confirm the deletion.\n\n' +
      'This action is irreversible. All your sessions, messages, learnings, profile data, and account will be permanently removed.',
  },
  {
    title: 'Contact',
    content:
      'If you have questions about your privacy or wish to exercise your data rights, please contact us:\n\n' +
      'Email: privacy@heyotis.app\n\n' +
      'We aim to respond to all privacy-related enquiries within 30 days.',
  },
];

export default function PrivacyScreen() {
  return (
    <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <View style={styles.header}>
        <View style={{ flex: 1 }}>
          <Text style={styles.title}>Privacy Policy</Text>
          <Text style={styles.subtitle}>How we handle your data</Text>
        </View>
        <TouchableOpacity onPress={() => router.back()} style={styles.closeBtn} activeOpacity={0.7}>
          <IconX size={18} color={Colors.midBrown} />
        </TouchableOpacity>
      </View>
      <ScrollView style={{ flex: 1 }} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.intro}>
          Hey Otis is built on the principle of privacy by design. Your relationship is personal, and your data should be too. This policy explains exactly what we collect, how it is used, and the control you have over it.
        </Text>

        <Text style={styles.effectiveDate}>Effective date: 8 April 2026</Text>

        {SECTIONS.map((section, i) => (
          <View key={i} style={styles.card}>
            <Text style={styles.cardTitle}>{section.title}</Text>
            <Text style={styles.cardContent}>{section.content}</Text>
          </View>
        ))}

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.cream },
  header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8 },
  title: { fontFamily: Fonts.displaySemiBold, fontSize: 26, color: Colors.charcoal },
  subtitle: { fontFamily: Fonts.body, fontSize: 14, color: Colors.midBrown, marginTop: 4 },
  closeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.creamDark, alignItems: 'center', justifyContent: 'center', marginTop: 4 },
  content: { paddingHorizontal: 20, paddingTop: 12 },
  intro: { fontFamily: Fonts.body, fontSize: 14, color: Colors.warmBrown, lineHeight: 22, marginBottom: 8 },
  effectiveDate: { fontFamily: Fonts.bodyMedium, fontSize: 12, color: Colors.midBrown, marginBottom: 20 },
  card: { backgroundColor: Colors.warmWhite, borderWidth: 1, borderColor: Colors.sand, borderRadius: Radius.lg, padding: 20, marginBottom: 16 },
  cardTitle: { fontFamily: Fonts.displaySemiBold, fontSize: 18, color: Colors.charcoal, marginBottom: 10 },
  cardContent: { fontFamily: Fonts.body, fontSize: 14, color: Colors.warmBrown, lineHeight: 22 },
});
